spring:
  data:
    rest:
      base-path: /api
  datasource:
    url: jdbc:postgresql://localhost/CV
    username: kutik
    password: lezcisobe
  jpa:
    generate-ddl: true
security:
  user:
    name: kutik
    password: kutik
    role: USER