spring:
  resources:
    cache-period: 0
    chain:
      cache: false
  cache:
    type: NONE
  datasource:
    url: jdbc:postgresql://localhost/CV
    username: kutik
    password: lezcisobe
  jpa:
    generate-ddl: true
    #hibernate:
      #ddl-auto: create
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE